import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: "var(--primary)",
        secondary: "var(--secondary)",
        primaryVariant: "var(--primary-variant)",
        secondaryVariant: "var(--secondary-variant)",
        darksteelblue: 'var(--color-darksteelblue)',
        darksdeepskyblueVariant: 'var(--color-darksteelblue-variant)',
        deepskyblue: 'var(--color-deepskyblue)',
        deepskyblueVariant: 'var(--color-deepskyblue-variant)',
        lightseagreen: 'var(--color-lightseagreen)',
        lightseagreenVariant: 'var(--color-lightseagreen-variant)',
        darkaqua: 'var(--color-darkaqua)',
        darkaquaVariant: 'var(--color-darkaqua-variant)',
        darkgreen: 'var(--color-darkgreen)',
        darkgreenVariant: 'var(--color-darkgreen-variant)',
        peachpuff: 'var(--color-peachpuff)',
        peachpuffVariant: 'var(--color-peachpuff-variant)',
        darkpapayawhip: 'var(--color-darkpapayawhip)',
        darkpapayawhipVariant: 'var(--color-darkpapayawhip-variant)',
        salmon: 'var(--color-salmon)',
        salmonVariant: 'var(--color-salmon-variant)',
        darkcrimson: 'var(--color-darkcrimson)',
        darkcrimsonVariant: 'var(--color-darkcrimson-variant)',
        orchid: 'var(--color-deepskyblue)',
        orchidVariant: 'var(--color-orchid-variant)',
        darklavender: 'var(--color-darklavender)',
        darklavenderVariant: 'var(--color-darklavender-variant)',
        blueviolet: 'var(--color-blueviolet)',
        bluevioletVariant: 'var(--color-blueviolet-variant)',
        lavender: 'var(--color-lavender)',
        lavenderVariant: 'var(--color-lavender-variant)',
        lemonchiffon: 'var(--color-lemonchiffon)',
        lemonchiffonVariant: 'var(--color-lemonchiffon-variant)',
        darkkhaki: 'var(--color-darkkhaki)',
        darkkhakiVariant: 'var(--color-darkkhaki-variant)',
        gold: 'var(--color-gold)',
        goldVariant: 'var(--color-gold-variant)',
        darkmoccasin: 'var(--color-darkmoccasin)',
        darkmoccasinVariant: 'var(--color-darkmoccasin-variant)',
      },
    },
  },
  plugins: [],
} satisfies Config;
