import { AnimeType } from "@/bounded-contexts/video-search-context/domain/model/anime";

const ANIME_LIST: AnimeType[] = [
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghuaworld.com/wp-content/uploads/2023/01/673mx8s4flp_4j84ou0q_021015.webp',
    title: 'Battle through the Heaven',
    summary: '',
    originalTitle: '斗破苍穹年番',
    subtitle: 'Dou Po Cang Qiong',
    studio: 'Foch Films',
    publishedBy: '',
    publishedAt: new Date('2021-01-01'),
    releaseAt: new Date('2023-01-2'),
    updatedAt: new Date('2025-01-22'),
    lastEpisode: 132,
    totalEpisodes: 0,
  },

  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEju8iJOcYSXkaW0K_wZ4O9Pm5_YdFbmuMK53avk6FZa7VKCCsJP9UZye0LOmcNeY_X7BtLD-xLKR_7d5d5EazuCPX4y0MNUdsfBWKELeAAzYmukZFED-D6K40x_qjjTNN2sBQtQn6R7zzPLi-LXZZhRGBGsKfvHE2rq-7XGd9MJtx_tmV5alqsDYFeXlKpc/w600/p2912735939.webp',
    title: 'Perfect world',
    summary: 'Né dans un monde unique où les villages se battent pour obtenir le pouvoir et le contrôle, le personnage principal, Shi Hao, est un génie béni par les cieux né dans les conditions les plus pauvres. Son clan, cependant, a un passé mystérieux. Pour se lever et devenir le génie qu’il est censé être, le clan met tout en œuvre pour aider sa culture alors qu’il combat des monstres fanatiques et s’engage dans des luttes de pouvoir avec d’autres clans. Son voyage l’amènera à travers des terres inconnues jusqu’à ce qu’il soit capable de devenir une personne qui peut vraiment secouer le monde.',
    originalTitle: '完美世界',
    subtitle: 'Wanmei Shijie',
    studio: 'Foch Films',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 200,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgj9f0v1-ppUtTBO4nyzBZUgP-N5GsZfal9tl9Itej8IZSeYIeXrwbcx-7dfjac2OQ0we5nUJ3PWwi26JtFOAAI23wnmBL-eqtrr4Z69RjKJv2cc2F298bCrTdo_x1cVTJJOCRLHRlcUhsMzH34U3k_iaCFU9Y012dUZ7bUjYlLm_H_5yrngZslXFQKImnP/w600/ezgif-1-57ce58b669.webp',
    title: 'Soul Land',
    summary: 'Tang San est l’un des disciples les plus prestigieux du clan d’art martial Tang Sect et sans égal dans l’utilisation d’armes cachées. Avec de grandes attentes, les anciens de la secte croient que son avenir sera brillant ; Pourtant, Tang choisit d’abandonner cette vie au prix de l’obtention des traditions interdites de la secte – une action passible de la peine de mort. Tang, maintenant satisfait de son ascension de la connaissance, ne voit aucune raison de continuer à vivre et saute de Hell’s Peak, mais il ne savait pas que ce ne serait pas la fin de son existence. Dans le continent de Douluo, les forts l’emportent et les faibles périssent. Chaque personne possède un esprit inné, dont certains peuvent être cultivés et renforcés, conférant à son utilisateur divers avantages. Ceux qui sont nés avec de tels esprits peuvent devenir Spirit Masters, une profession considérée comme l’une des plus nobles du continent. Tang, réincarné dans ce monde étrange, ne connaît que la vie d’un fils de forgeron. À l’âge de six ans, il participe à la cérémonie du Spirit Master et découvre que son esprit est Blue Silver Grass – soi-disant l’esprit le plus inutile du monde. En revanche, cependant, il possède un fort pouvoir spirituel. Maintenant, aidé également par les souvenirs de sa vie antérieure, l’avenir de Tang en tant que maître des esprits n’est en aucun cas sombre.',
    originalTitle: '斗罗大陆',
    subtitle: 'Douluo Dalu',
    studio: 'Sparkly Key Animation Studio',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 85,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghuaworld.com/wp-content/uploads/2023/09/0-2.jpeg_065033.webp',
    title: 'Renegade Immortal',
    summary: '',
    originalTitle: '仙逆',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 72,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://www.themoviedb.org/t/p/w1280/7rP8IfBsSuoKGiP4pKDR6X57Hf1.jpg',
    title: 'Shrouting the heavens',
    summary: '',
    originalTitle: '遮天',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 93,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://media.senscritique.com/media/000021237038/300/swallowed_star.png',
    title: 'Swallowed star',
    summary: 'Un jour, un virus RR inconnu est apparu sur terre et le monde est tombé dans le désastre. Les animaux infectés se transforment en monstres effrayants et attaquant massivement. Lorsque les humains font face à la destruction, ils construisent des murs et construisent des villes de base comme dernier bastion de l’homme. Les épreuves vécues par l’humanité au cours de cette période sont appelées la « Période du Nirvana ». Dans les environnements de vie extrêmes, le pouvoir humain progresse et évolue également progressivement, et les arts martiaux émergent, et le pouvoir humain augmente qualitativement par rapport à avant. Et le meilleur d’entre eux s’appelle les Warriors. Luo Feng, 18 ans, aspire également à être l’un d’entre eux. Actuellement, elle passera l’examen d’entrée à l’université et devra faire un choix à un carrefour de sa vie, mais soudain, une attaque de monstre affecte la trajectoire de sa vie. Sous la menace de monstres puissants, les habitants de la ville sont en danger, mais les militaires sont impuissants. Un seul soldat s’est levé et a maintenu la sécurité de la ville de base. Luo Feng est infecté par une force guerrière et décide secrètement de devenir un combattant pour protéger ses proches. C’est le début de tout, le point de départ du voyage de Luo Feng en tant qu’artiste martial, et aussi le début de sa vie légendaire. Luo Feng aspire à être un artiste martial, mais le chemin à parcourir n’est pas facile. La première chose à laquelle il doit faire face est l’influence de l’environnement extérieur qui ne lui est pas visible. L’état de santé de la famille de Luo Feng était alarmant et la vie était difficile, ses parents ne pouvaient pas fournir plus d’aide et ne pouvaient compter que sur ses propres efforts. En fin de compte, sous un travail acharné constant, Luo Feng continue d’explorer son propre potentiel et est reconnu par ses capacités accrues et son auto-amélioration. Non seulement cela, Luo Feng a non seulement assumé le fardeau de soutenir la famille, mais a également rejoint d’autres combattants de la justice pour affronter des monstres maléfiques afin de protéger la patrie de l’humanité et pour une meilleure survie et un meilleur développement de l’humanité. Dans une situation apocalyptique désespérée, Luo Feng et les autres soldats peuvent-ils chasser les monstres et réussir à protéger le monde humain ?',
    originalTitle: '吞噬星空',
    subtitle: 'Tunshi Xinkong',
    studio: 'Sparkly Key Animation Studio',
    publishedBy: '',
    publishedAt: new Date('2020-01-01'),
    releaseAt: new Date('2023-01-3'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 155,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghualist.com/wp-content/uploads/2023/11/a-record-of-mortal-journey-to-immortality-2.jpg',
    title: 'A Mortal’s Journey to Immortality',
    summary: '',
    originalTitle: '凡人修仙传',
    subtitle: 'Immortal Ascension',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 127,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghuaworld.com/wp-content/uploads/2025/01/1000025379.webp',
    title: 'Martial universe S5',
    summary: '',
    originalTitle: '武动乾坤',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 12,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj1zYsfCdfes3rCzaZ3WhABObshR1MjpqMkaC6cGVVgC5nnyXYOa9U49TmFNcl07gV_1LYzLxgmv9ZOtGgWcnwtdURNzHAK6kSKSsgmUOzVtVgWpB4rBU8eSmX2xIKqC6jAwPhriKsVOfjn18jI8rwasLfMb8dvMUsmXChWnTXOi750LkhESTj1zfKu2hGD/w600/p2899481519.webp',
    title: 'My senior brother is too steady',
    summary: '',
    originalTitle: '师兄啊师兄',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 71,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjl9bKjFI6x6wJVKtcOpqb95q4ZBSrul1T6HYRidBVKLZBuChxg-pqE1STH9Gn9PtUexfdWUUQZPnoy6A6dpnoYJewkDUR9M0c16wDmvanRgQmgU-jd-satwTZEsf_FdmnWkCJKzirv0Ta7PekB413oQBKgMxuE0oxBg2WJ4eBPJajyBW9tY1d5hV1SjMpi/w600/p2882471067.webp',
    title: 'Tomb of fallen gods',
    summary: '',
    originalTitle: '神墓',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 71,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://luciferdonghua.in/wp-content/uploads/2023/03/legend-of-xianwu-xianwu-emperor-season-2.webp',
    title: 'Legend of xianwu',
    summary: '',
    originalTitle: '仙武传',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 99,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghualist.com/wp-content/uploads/2023/11/stellar-transformation-xing-chen-bian-2.jpg',
    title: 'Stellar Transformations',
    summary: 'Ayant des problèmes avec ses méridiens et ainsi rendu incapable de pratiquer les arts internes, Qin Yu vit en isolement avec grand-père Lian. Pour remonter le moral d’un Qin Yu déprimé, Lian lui offre un oiseau particulier, que l’ancien nomme Xiao Hei. Voulant être reconnu par son père, Qin Yu s’engage sur la voie de la cultivation. Avec la méthode d’entraînement rigoureuse de Zhao Yunxing, il s’efforce de surmonter ses obstacles physiologiques et de devenir un expert des arts extérieurs. Alors qu’il se repose d’une de ces séances d’entraînement, Qin Yu découvre un cristal rouge qui, à sa grande surprise, fusionne avec son corps. À son insu, cette transformation subtile donne à Qin Yu des capacités étonnantes qui l’aideront alors qu’il entreprend, avec Xiao Hei en remorque, de prouver qu’il est digne de la reconnaissance de son père.',
    originalTitle: '星辰变',
    subtitle: 'Xing Chen Bian',
    studio: 'Foch Films',
    publishedBy: '',
    publishedAt: new Date('2018-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-29'),
    lastEpisode: 83,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiX1sCLQO7vRzL-xeMXDSt8IRYz27Ttup_ydI2VslhIFatoMcCJvkwvmAIA7aB8mbepJRQy8BNlXmGPbC-F95LmyQN54pS3lNf1hQGyLNzkURz_Qfo1HOg3DpK0s7BI9aS5gR6-mqGBMMa4Pa3AQNL9FlBRLKpzjDPKViP286eNlM9z-SgliMxSTkG0RCGn/w600/p2916595576.webp',
    title: 'Tales of herding gods',
    summary: '',
    originalTitle: '牧神记',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 12,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://anime4i.vip/wp-content/uploads/2024/10/Tiger-Crane-Hu-He-Yao-Shi-Lu%E8%99%8E%E9%B9%A4%E5%A6%96%E5%B8%88%E5%BD%95.webp',
    title: 'Tiger Crane',
    summary: '',
    originalTitle: '虎鹤妖师录',
    subtitle: 'Hu He Yao Shi Lu',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 17,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'http://i.imgur.com/fVXplB7.jpeg',
    title: 'Every disciple is a Boss',
    summary: '',
    originalTitle: '徒弟个个是大佬',
    subtitle: 'Over Goddess',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 24,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://i.pinimg.com/originals/db/dc/9c/dbdc9c456231edf8ac5dc5e71cbc1b71.jpg',
    title: 'Sword of coming',
    summary: '',
    originalTitle: '剑来',
    subtitle: 'Jian Lai',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 17,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://m.media-amazon.com/images/M/MV5BZDY3YjdjM2ItZDZmMC00NzY0LTllNDMtMTVhYzNlNDRkOWY5XkEyXkFqcGc@.jpg',
    title: 'A Will Eternal',
    summary: '',
    originalTitle: '一念永恒',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 133,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://simkl.in/posters/16/16667515bc27557d5d_m.jpg',
    title: 'World of immortals',
    summary: '',
    originalTitle: '长生界',
    subtitle: 'Chang Sheng Jie',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 13,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://m.media-amazon.com/images/M/MV5BMTljZjQ4MDMtZWQwZS00ZDY2LWJlZjUtYjc4ODQ3NTc1NjU5XkEyXkFqcGc@.jpg',
    title: 'Dragon Prince Yuan',
    summary: '',
    originalTitle: '元尊',
    subtitle: 'yuan zun',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 16,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhfshbqDYekJ2PoM2qY66k2_CfFPX8znfRpRFLrUqGvUNDuZRmuMoS_nI5s6KvleyLfSxh-xvMEO78LJe6MFup_lfVA8BF_BSFMQ3VLv8jNae5JX1kH8cRr-JqGjUiwKOPoAAtgpvpfY1N_zFpH6aupNsPLxC9JfRHfQnoME7zg0PvxKPcWrtqWGltcOfmA/w600/p2619010287.webp',
    title: 'Painting Rivers and Lakes',
    summary: '',
    originalTitle: '画江湖之不良人',
    subtitle: 'tua Jianghu: Buliang Ren',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 16,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiDPrpz0EJXKKL9QFv4BpMNlA5vhznIhw3Lg-lFG0anHov4pS7vBXLXzxOZhWWroSYqeapZR9QFP1pDGMveYMf6c1mptVrR_G-6hc3EAvCxiiBJjorsDyYY8l3NC7D50DTQoYLUWPynfQlOM2jSH8s625uK0JdK0xEJyVE61ggVrncOVbVVQuFUSPKmRZmg/w600/p2900256576.webp',
    title: 'Ling Long',
    summary: '',
    originalTitle: '灵笼',
    subtitle: 'Ling Cage, Spirit Cage: Incarnation',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 15,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghuastream.org/wp-content/uploads/2024/03/Immediately-Season-3-%E6%B0%B8%E7%94%9F-%E7%AC%AC%E4%B8%89%E5%AD%A3-IMMORTAL-Season-3-Yong-Sheng-Season-3.jpg',
    title: 'Immortality',
    summary: '',
    originalTitle: '永生',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 16,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://i2.wp.com/kungfutv.net/wp-content/uploads/2023/12/apotheosis-season2.jpg',
    title: 'Apotheosis',
    summary: '',
    originalTitle: '百炼成神',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 103,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://i0.wp.com/luciferdonghua.in/wp-content/uploads/2022/02/dragons-disciple-LUCIFER-DONGHUA.webp?fit=641,971&ssl=1',
    title: 'Dragon’s disciple',
    summary: '',
    originalTitle: '龙蛇演义',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 16,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghuastream.org/wp-content/uploads/2024/04/Legend-of-Soldier%E5%B0%8F%E5%85%B5%E4%BC%A0%E5%A5%87-Xiao-Bing-Chuanqi.jpg',
    title: 'Legend of Soldier',
    summary: '',
    originalTitle: '小兵传奇',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 24,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghuaworld.com/wp-content/uploads/2023/12/Alchemy-Supreme-Dan-Dao-Zhizun-01.webp',
    title: 'Alchemy Supreme',
    summary: '',
    originalTitle: '丹道至尊',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 108,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://lmanime.com/wp-content/uploads/2022/08/Ni-Tian-Zhizun-768x1077-1.jpg',
    title: 'Against the sky supreme',
    summary: '',
    originalTitle: '逆天至尊',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 375,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://luciferdonghua.in/wp-content/uploads/2021/11/martial-master-lucifer-donghua-chinese-anime.webp',
    title: 'Martial Master',
    summary: 'Le protagoniste Qin Chen, qui était à l’origine le plus grand génie du domaine militaire, a été conspiré par le peuple pour tomber dans le canyon de la mort dans la terre interdite du continent. Qin Chen, qui était inévitablement mort, a déclenché de manière inattendue le pouvoir de la mystérieuse épée ancienne. Trois cents ans plus tard, dans une partie reculée du continent de Tianwu, un garçon du même nom hérite accidentellement de la volonté de Qin Chen. En tant que petit-fils bien-aimé du roi Dingwu de l’armée nationale Daqi, en raison de la naissance du père biologique, la mère et le fils ont été traités froidement dans le palais de Dingwu et ont vécu ensemble. Afin de réécrire le mythe de l’homme fort dans l’espoir du soleil, et de protéger tout ce qu’il aime, Qin Chen a résolument pris la responsabilité de maintenir les cinq royaumes du monde et a remis le pied sur la route des arts martiaux.',
    originalTitle: '武神主宰',
    subtitle: 'Wushen Zhuzai',
    studio: 'Ruo Hong Culture',
    publishedBy: '',
    publishedAt: new Date('2020-01-01'),
    releaseAt: new Date('2023-01-16'),
    updatedAt: new Date('2025-01-22'),
    lastEpisode: 515,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://m.media-amazon.com/images/M/MV5BOTFkNjI4ODYtYWJkMC00N2YxLTljY2EtNTkzNzIzM2NjYzIyXkEyXkFqcGc@.jpg',
    title: 'Martial Peak',
    summary: '',
    originalTitle: '武炼巅峰',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 24,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://lmanime.com/wp-content/uploads/2022/08/LM.jpg',
    title: 'The success of empyrean xuan emperor',
    summary: '',
    originalTitle: '九天玄帝诀',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 111,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://i1.wp.com/comicxy.com/wp-content/uploads/2022/11/Myriad-Realms-Supreme-Wan-Jie-Zhizun.png',
    title: 'Myriad Realms Supreme',
    summary: '',
    originalTitle: '万界至尊',
    subtitle: 'Wan Jie Zhi zun - The sovereign of all realms',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 184,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghuafans.org/wp-content/uploads/2024/09/my-wechat-is-connected-to-dragon-palace.jpg',
    title: 'My WeChat is connected to Dragon Palace',
    summary: '',
    originalTitle: '我的微信通龙宫',
    subtitle: 'Wo de Wei Xin Tong Longgong',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 47,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghuastream.org/wp-content/uploads/2024/10/%E4%B8%87%E7%95%8C%E4%B8%BB%E5%AE%B0-Lord-of-All-Realms-Master-of-All-Worlds.jpg',
    title: 'Lord of Wonderlands',
    summary: '',
    originalTitle: '万界主宰',
    subtitle: 'Lord of all worlds - Dominator of Myriad Realms',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 30,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://donghuafans.org/wp-content/uploads/2024/10/Divine-Lord-of-the-Heavens.jpg',
    title: 'Divine Lord of the Heavens',
    summary: '',
    originalTitle: '神道帝尊',
    subtitle: 'Shinto Emperor : rebirth of Qin Yang',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 31,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://animexin.dev/wp-content/uploads/2024/11/Wu-Ni-Martial-Inverse.webp',
    title: 'Martial Inverse',
    summary: '',
    originalTitle: '武逆',
    subtitle: 'Martial Reversal',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 16,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://i3.wp.com/luciferdonghua.org/wp-content/uploads/2023/02/one-hundred-thousand-years-of-qi-refining-lucifer-donghua.webp',
    title: 'One hundred thousand years of gas refining',
    summary: '',
    originalTitle: '炼气十万年',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 199,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://chineseanimes.com/wp-content/uploads/2024/07/Lingwu-Continent.webp',
    title: 'Lingwu Continent',
    summary: '',
    originalTitle: '灵武大陆',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 199,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://i0.wp.com/kungfutv.net/wp-content/uploads/2023/09/Glorious-Revenge-of-Ye-Feng-22.jpg',
    title: 'Glorious Revenge of Ye Feng',
    summary: '',
    originalTitle: '独步万古',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 128,
    totalEpisodes: 0,
  },
  { uid: crypto.randomUUID().toString(),
    type: 'series',
    status: 'ongoing',
    thumbnail: 'https://media.themoviedb.org/t/p/w300_and_h450_bestv2/8Ot1C0nqDvBVcbsBo7Olnbq4yHN.jpg',
    title: 'The Most Proud Swordsman',
    summary: '',
    originalTitle: '人间最得意',
    subtitle: '',
    studio: '',
    publishedBy: '',
    publishedAt: new Date('2017-01-01'),
    releaseAt: new Date('2023-01-12'),
    updatedAt: new Date('2025-01-26'),
    lastEpisode: 71,
    totalEpisodes: 0,
  },
]

export default ANIME_LIST;
