import serie from '../../public/series.json';

const FAVORITES = [
    { uid: crypto.randomUUID().toString(), title: 'Battle through the Heaven'                                  , subtitle: ''                                            , lastEpisode: '125', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Perfect world'                                              , subtitle: ''                                            , lastEpisode: '197', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Soul land 2 '                                               , subtitle: ''                                            , lastEpisode: '82', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Renegate immortal '                                         , subtitle: ''                                            , lastEpisode: '70', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Shrouting the heavens'                                      , subtitle: ''                                            , lastEpisode: '91', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Swallowed star'                                             , subtitle: ''                                            , lastEpisode: '153', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'My senior brother is too steady'                            , subtitle: ''                                            , lastEpisode: '71', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Martial universe season 5'                                  , subtitle: ''                                            , lastEpisode: '3', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Tomb of fallen gods'                                        , subtitle: ''                                            , lastEpisode: '39', total: 0 },

    { uid: crypto.randomUUID().toString(), title: 'Alchemy Supreme'                                            , subtitle: ''                                            , lastEpisode: '107', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Against the sky supreme'                                    , subtitle: ''                                            , lastEpisode: '373', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'martial master'                                             , subtitle: ''                                            , lastEpisode: '510', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'martial peak'                                               , subtitle: ''                                            , lastEpisode: '18', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Martial inverse'                                            , subtitle: ''                                            , lastEpisode: '14', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Legend of xuan emperor'                                 , subtitle: ''                                            , lastEpisode: '111', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Ancient Lords (Yishi Zhi Zun)'                              , subtitle: ''                                            , lastEpisode: '87', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Lord of all lords'                                          , subtitle: ''                                            , lastEpisode: '26', total: 26 },
    { uid: crypto.randomUUID().toString(), title: 'master of all worlds season 1 - lord of wonderlands'        , subtitle: ''                                            , lastEpisode: '25', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'divine lord of the heavens'                                 , subtitle: ''                                            , lastEpisode: '26', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'myriad realms supreme'                                      , subtitle: ''                                            , lastEpisode: '181', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Supreme god emperor'                                        , subtitle: ''                                            , lastEpisode: '455', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'one hundred thousand years of gas refining'                 , subtitle: ''                                            , lastEpisode: '199', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'A Will Eternal season 3'                                    , subtitle: ''                                            , lastEpisode: '31', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Myth of the ancients (wangu shenhua)'                       , subtitle: ''                                            , lastEpisode: '253', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'ten thousands worlds'                                       , subtitle: ''                                            , lastEpisode: '293', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Spirit sword sovereign'                                     , subtitle: ''                                            , lastEpisode: '559', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Supreme Sword God season 2'                                 , subtitle: ''                                            , lastEpisode: '68', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Proud Swordsman'                                            , subtitle: ''                                            , lastEpisode: '71', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Lingwu Continent'                                           , subtitle: ''                                            , lastEpisode: '52', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Glorious Revenge of Ye Feng'                                , subtitle: ''                                            , lastEpisode: '128', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The path to heaven'                                         , subtitle: ''                                            , lastEpisode: '16', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'My WeChat is connected to Dragon Palace'                    , subtitle: ''                                            , lastEpisode: '47', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'I annoyed millions of cultivators'                          , subtitle: ''                                            , lastEpisode: '175', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The strongest sect of all time'                             , subtitle: ''                                            , lastEpisode: '26', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Every disciple is a Boss season 1'                          , subtitle: ''                                            , lastEpisode: '24', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Immortal Doctor'                                        , subtitle: ''                                            , lastEpisode: '34', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'I have an infinite enlightenment'                           , subtitle: ''                                            , lastEpisode: '25', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Land of the keyboard immortal'                              , subtitle: ''                                            , lastEpisode: '80', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'King of loose cultivator'                                   , subtitle: ''                                            , lastEpisode: '44', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Everyone in my sect is undercover except me'                , subtitle: ''                                            , lastEpisode: '30', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Hidden dragon in the sky'                                   , subtitle: ''                                            , lastEpisode: '6', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'the war of cards'                                           , subtitle: ''                                            , lastEpisode: '7', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Five elements god of war'                                   , subtitle: ''                                            , lastEpisode: '80', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Westward Season 5'                                      , subtitle: ''                                            , lastEpisode: '63', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Fairy Trail'                                                , subtitle: ''                                            , lastEpisode: '40', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'God of war alliance'                                        , subtitle: ''                                            , lastEpisode: '63', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'World of immortals'                                         , subtitle: ''                                            , lastEpisode: '12', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Peerless soul of war'                                       , subtitle: ''                                            , lastEpisode: '177', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Shinto Emperor : rebirth of Qin Yang'                       , subtitle: ''                                            , lastEpisode: '28', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Rebirth of the sword Patriarch'                             , subtitle: ''                                            , lastEpisode: '8', total: 0 },

    { uid: crypto.randomUUID().toString(), title: 'Tales of demons and gods'                                   , subtitle: ''                                            , lastEpisode: '380', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Magic chef of ice and fire'                                 , subtitle: ''                                            , lastEpisode: '155', total: 155 },
    { uid: crypto.randomUUID().toString(), title: 'The Peak of True Martial Arts'                              , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Apotheosis'                                                 , subtitle: ''                                            , lastEpisode: '103', total: 103 },

    { uid: crypto.randomUUID().toString(), title: 'Peerless Martial Spirit'                                    , subtitle: ''                                            , lastEpisode: '418', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Peerless Battle Spirit'                                     , subtitle: ''                                            , lastEpisode: '62', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'carp reborn (yuan long) season 3'                           , subtitle: ''                                            , lastEpisode: '3', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Throne of Seal (shen yin  wang zuo)'                        , subtitle: ''                                            , lastEpisode: '141', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Dragon’s disciple'                                          , subtitle: ''                                            , lastEpisode: '16', total: 16 },
    { uid: crypto.randomUUID().toString(), title: 'great journey of teenagers season 4'                        , subtitle: ''                                            , lastEpisode: '2', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'A Mortal’s Journey to Immortality'                          , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Stellar Tranformation'                                      , subtitle: ''                                            , lastEpisode: '', total: 0 },

    { uid: crypto.randomUUID().toString(), title: 'Hidden Sect Leader'                                         , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Spiritual Lord of Chaos'                                    , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Secrets of Star Divine Arts'                            , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Grandmaster of Alchemy'                                     , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The great ruler'                                            , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'against the gods - nitian xie shen'                         , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Stellar transformation'                                     , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Nirvana of storm rider'                                     , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Mortal journey to immortality'                              , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Legend of xianwu'                                           , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Yishi Zhi Zun '                                             , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'tales of dark river'                                        , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Throne of seal'                                             , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Jade Dynasty 7'                                             , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Thousand Autumn'                                            , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Legend of the Taiyi Sword Immortal'                     , subtitle: ''                                            , lastEpisode: '17', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Stop at the level of Refining Qi for 100,000 years'         , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Soul of light'                                              , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The island of sailing'                                      , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Purple river'                                               , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Word of Honor'                                              , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Millenniums Of Warring States'                              , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Galaxy Emperor'                                         , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'five elements'                                              , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Dinghai Floating Records'                                   , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Thousands of worlds'                                        , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Epic of Divinity Light'                                     , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Immortals of the Godless Age'                               , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Martial God'                                                , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'egend of Exorcism'                                          , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Legend of Tang'                                             , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Young Brewmaster Adventure'                             , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Legend of sword domain'                                     , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'ancient Myth'                                               , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Legend of Dragon Soldier'                               , subtitle: ''                                            , lastEpisode: '17', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'My Journey in an Alternate World'                           , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Tale of The Spirit Stone'                               , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Wonderland of ten thousands'                                , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The lord of no boundary'                                    , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The God of Ten Thousand Realms'                             , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Supreme Lord of Galaxy'                                     , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'The Sovereign of All Realms'                                , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'mad demon lord'                                             , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Snow Eagle Lord'                                            , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Lord of planets'                                            , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Chronicles of Everlasting Wind and Sword Rain'              , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Chief Soul Manipulator'                                     , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Meteor Magic Sword'                                         , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Dragon Prince Yuan'                                         , subtitle: ''                                            , lastEpisode: '', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Divine Dragon Start Lord (shenlong xinzhu)'                 , subtitle: ''                                            , lastEpisode: '17', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Rise of the dragon'                                         , subtitle: ''                                            , lastEpisode: '17', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Dragon star master'                                         , subtitle: ''                                            , lastEpisode: '32', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Sword of coming'                                            , subtitle: ''                                            , lastEpisode: '17', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Jin Wu Wei'                                                 , subtitle: ''                                            , lastEpisode: '16', total: 16 },
    { uid: crypto.randomUUID().toString(), title: 'Shoa Nian Ge Xing Season 4'                                 , subtitle: ''                                            , lastEpisode: '2', total: 0 },
    { uid: crypto.randomUUID().toString(), title: 'Azure Legacy season 2'                                      , subtitle: ''                                            , lastEpisode: '37', total: 0 },
    ...serie
]

export default FAVORITES;