import serie from '../../public/series.json';

const FAVORITES = [
    ...serie,
    { id: crypto.randomUUID().toString(), title: 'Battle through the Heaven'                              , lastEpisode: '125', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Perfect world'                                          , lastEpisode: '197', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Soul land 2 '                                           , lastEpisode: '82', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Renegate immortal '                                     , lastEpisode: '70', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Shrouting the heavens'                                  , lastEpisode: '91', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Swallowed star'                                         , lastEpisode: '153', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'My senior brother is too steady'                        , lastEpisode: '71', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Martial universe season 5'                              , lastEpisode: '3', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Tomb of fallen gods'                                    , lastEpisode: '39', total: 0 },

    { id: crypto.randomUUID().toString(), title: 'Alchemy Supreme'                                        , lastEpisode: '107', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Against the sky supreme'                                , lastEpisode: '373', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'martial master'                                         , lastEpisode: '510', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'martial peak'                                           , lastEpisode: '18', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Martial inverse'                                        , lastEpisode: '14', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Legend of xuan emperor'                             , lastEpisode: '111', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Ancient Lords (Yishi Zhi Zun)'                          , lastEpisode: '87', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Lord of all lords'                                      , lastEpisode: '26', total: 26 },
    { id: crypto.randomUUID().toString(), title: 'master of all worlds season 1 - lord of wonderlands'    , lastEpisode: '25', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'divine lord of the heavens'                             , lastEpisode: '26', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'myriad realms supreme'                                  , lastEpisode: '181', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Supreme god emperor'                                    , lastEpisode: '455', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'one hundred thousand years of gas refining'             , lastEpisode: '199', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'A Will Eternal season 3'                                , lastEpisode: '31', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Myth of the ancients (wangu shenhua)'                   , lastEpisode: '253', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'ten thousands worlds'                                   , lastEpisode: '293', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Spirit sword sovereign'                                 , lastEpisode: '559', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Supreme Sword God season 2'                             , lastEpisode: '68', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Proud Swordsman'                                        , lastEpisode: '71', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Lingwu Continent'                                       , lastEpisode: '52', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Glorious Revenge of Ye Feng'                            , lastEpisode: '128', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The path to heaven'                                     , lastEpisode: '16', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'My WeChat is connected to Dragon Palace'                , lastEpisode: '47', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'I annoyed millions of cultivators'                      , lastEpisode: '175', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The strongest sect of all time'                         , lastEpisode: '26', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Every disciple is a Boss season 1'                      , lastEpisode: '24', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Immortal Doctor'                                    , lastEpisode: '34', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'I have an infinite enlightenment'                       , lastEpisode: '25', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Land of the keyboard immortal'                          , lastEpisode: '80', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'King of loose cultivator'                               , lastEpisode: '44', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Everyone in my sect is undercover except me'            , lastEpisode: '30', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Hidden dragon in the sky'                               , lastEpisode: '6', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'the war of cards'                                       , lastEpisode: '7', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Five elements god of war'                               , lastEpisode: '80', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Westward Season 5'                                  , lastEpisode: '63', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Fairy Trail'                                            , lastEpisode: '40', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'God of war alliance'                                    , lastEpisode: '63', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'World of immortals'                                     , lastEpisode: '12', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Peerless soul of war'                                   , lastEpisode: '177', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Shinto Emperor : rebirth of Qin Yang'                   , lastEpisode: '28', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Rebirth of the sword Patriarch'                         , lastEpisode: '8', total: 0 },

    { id: crypto.randomUUID().toString(), title: 'Tales of demons and gods'                               , lastEpisode: '380', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Magic chef of ice and fire'                             , lastEpisode: '155', total: 155 },
    { id: crypto.randomUUID().toString(), title: 'The Peak of True Martial Arts'                          , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Apotheosis'                                             , lastEpisode: '103', total: 103 },

    { id: crypto.randomUUID().toString(), title: 'Peerless Martial Spirit'                                , lastEpisode: '418', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Peerless Battle Spirit'                                 , lastEpisode: '62', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'carp reborn (yuan long) season 3'                       , lastEpisode: '3', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Throne of Seal (shen yin  wang zuo)'                    , lastEpisode: '141', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Dragon’s disciple'                                      , lastEpisode: '16', total: 16 },
    { id: crypto.randomUUID().toString(), title: 'great journey of teenagers season 4'                    , lastEpisode: '2', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'A Mortal’s Journey to Immortality'                      , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Stellar Tranformation'                                  , lastEpisode: '', total: 0 },

    { id: crypto.randomUUID().toString(), title: 'Hidden Sect Leader'                                     , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Spiritual Lord of Chaos'                                , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Secrets of Star Divine Arts'                        , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Grandmaster of Alchemy'                                 , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The great ruler'                                        , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'against the gods - nitian xie shen'                     , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Stellar transformation'                                 , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Nirvana of storm rider'                                 , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Mortal journey to immortality'                          , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Legend of xianwu'                                       , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Yishi Zhi Zun '                                         , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'tales of dark river'                                    , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Throne of seal'                                         , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Jade Dynasty 7'                                         , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Thousand Autumn'                                        , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Legend of the Taiyi Sword Immortal'                 , lastEpisode: '17', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Stop at the level of Refining Qi for 100,000 years'     , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Soul of light'                                          , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The island of sailing'                                  , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Purple river'                                           , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Word of Honor'                                          , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Millenniums Of Warring States'                          , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Galaxy Emperor'                                     , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'five elements'                                          , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Dinghai Floating Records'                               , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Thousands of worlds'                                    , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Epic of Divinity Light'                                 , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Immortals of the Godless Age'                           , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Martial God'                                            , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'egend of Exorcism'                                      , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Legend of Tang'                                         , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Young Brewmaster Adventure'                         , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Legend of sword domain'                                 , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'ancient Myth'                                           , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Legend of Dragon Soldier'                           , lastEpisode: '17', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'My Journey in an Alternate World'                       , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Tale of The Spirit Stone'                           , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Wonderland of ten thousands'                            , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The lord of no boundary'                                , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The God of Ten Thousand Realms'                         , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Supreme Lord of Galaxy'                                 , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'The Sovereign of All Realms'                            , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'mad demon lord'                                         , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Snow Eagle Lord'                                        , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Lord of planets'                                        , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Chronicles of Everlasting Wind and Sword Rain'          , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Chief Soul Manipulator'                                 , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Meteor Magic Sword'                                     , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Dragon Prince Yuan'                                     , lastEpisode: '', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Divine Dragon Start Lord (shenlong xinzhu)'             , lastEpisode: '17', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Rise of the dragon'                                     , lastEpisode: '17', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Dragon star master'                                     , lastEpisode: '32', total: 0 },
    { id: crypto.randomUUID().toString(), title: 'Sword of coming'                                        , lastEpisode: '17', total: 0 },
]

export default FAVORITES;